### ISSUE TITLE
Analysis IDs have only 4 digits

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#10]
FeatureRequest:
Analysis IDs have only 4 digits which allows 27 analysis per day in a year. Would be nice to have one digit more to avoid reaching limitations.

**Comment by markov2** [comment]
To be able to estimate the urgency (its not a simple change): what it the predicted number of analysis you will make this year?

'''date +"%j"''' tells me today is the 274th of this year

**Comment by bsi-lz** [comment]
we are doing arround 15 analysis per day, but i think this is increasing. at the moment there is no urgency, but i think it would be useful in a later release.
