### ISSUE TITLE
No Config.pm error while there is a Config.pm present

### ISSUE THREAD

**Issue by akok-svb** [NCSC-NL/taranis3#11]
The error: 

`File does not exist: /root/etc/taranis.conf.xml at /home/taranis/sources/taranis-3.4.3/pm/Taranis/Config.pm line 21.
Installation stopped
`

The file Config.pm is present in all folders it should be.

**Comment by markov2** [comment]
See https://github.com/NCSC-NL/taranis3/wiki/Release-3.4.3 section 'Known Issues', first issue

**Comment by akok-svb** [comment]
It's not the install script, it's the Config.pm script. Removing the install script has no effect.

**Comment by markov2** [comment]
* akok-svb (notifications@github.com) [181004 06:39]:
> It's not the install script, it's the Config.pm script. Removing the
> install script has no effect.

When you remove the script which addresses the Config.pm incorrectly, then
there is no chance that the error is still there.  Probably you removed
the wrong script.
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net
