### ISSUE TITLE
installation issue on Centos 6

### ISSUE THREAD

**Issue by ivmp-ewl** [NCSC-NL/taranis3#13]
good Morning

I had some issue when I install taranis 3.4.4 on Centos 6. My knowledge in perl is very basic, so I just solve my issue ... maybe not in the best way.

- CPAN  installation,
It tell me to install it on my /root directory (instead of taranis directory) so there is right issue, even if I install manually cpan on taranis user, then restart the bootstrap installation.
So I rename the file 200.perl-cpan-setup to not be taken in count, then I install cpan in user taranis (cpan o conf init) with the url in the file 200.perl-cpan-setup plus our proxy, then I relaunch the taranis installation with no more bog error regarding cpan and package installed with cpan (I installed some package using cpan manually ... IO-Socket-SSL for instance), 

-  postgreSQL database.  
I had this error 

> DBD::Pg::st execute failed: ERROR:  relation "pg_extension" does not exist
LINE 1: SELECT extname FROM pg_extension;
                            ^ at /home/taranis/sources/taranis-3.4.4/install/422.postgres-startup line 
>
so I had to install manually postgresql 9
> rpm -Uvh https://yum.postgresql.org/9.1/redhat/rhel-6-x86_64/pgdg-centos91-9.1-4.noarch.rpm

- xml configuration
it seems that some xml file has to be recoverd from /opt/taranis/conf ... and my installation was a new one ... (finally I just copy all sources/taranis*/conf files to /opt/taranis/conf and it ran)

- Startfile and conf files
Some file require to start processes with systemctl .. but on Centos 6  I didn't have.
so I change these lines 

1. On 421.postgres-hba file

> #system "systemctl enable postgresql";
> system "service postgresql start";
> $? and die "ERROR: systemctl doesn't enable postgresql\n";
> 
> #system "systemctl restart postgresql";
> $? and die "ERROR: systemctl doesn't restart postgresql\n";
> 
> system "ps -C postgres >/dev/null";
> $? and die "ERROR: postgres not running\n";

2. on both apache conf file : ~/lib/apache-vhost-extra/*
- I had to modify because my apache was not a 2.4 

> Require         all granted

 to 
>    Order allow,deny
>   Allow from all

- I had to modify apache port listening taranis4u to let taranis and taranis4u run together.

3. - on file ~/taranis-3.4.4/perl5/Taranis/Command/Control.pm
I change this (but still not working verywell) : 

>  #my $cron_status = qx(systemctl status $service);
>  my $cron_status = qx(service $service status);

So this  issue is more regarding github :) . How can I help  and commit these informations, will I be able to do this on my own or not ? 

Another issue is regarding  a basic "how to", you had pdf file on taranis.ncsc websit, I had delete everything. I don't understand yet how to use some tools you provide, and some on taranis4u .will it be available somewhere ? feel free to contact me about this.

Thanks for your jobs  anyway.

Regards

**Comment by markov2** [comment]
This is actually not an issue in the strict sense, but installation help request.  These questions can better be directed to taranis@ncsc.nl  When unintended behavior is discover, then create separate issues for each of the problems.

> I had some issue when I install taranis 3.4.4 on Centos 6. My knowledge in perl is very basic, so I just solve my issue ... maybe not in the best way.

CentOS 6 is not supported.  Taranis 3.4 comes with brand new installation scripts, which try to install all facets of the application automatically... but those scripts do contain information about specific differences of Linux distributions.  The installation has been "ported" to CentOS 7, not CentOS 6 (yet)
(see https://github.com/NCSC-NL/taranis3/wiki/Install-Prepare-a-System#Supported_Linux_distributions)

Write an email to us convincing we need to support CentOS 6, and I will do the backport of the installation.

> CPAN  installation,
>  It tell me to install it on my /root directory (instead of taranis directory) so there is right issue, even if I install manually cpan on taranis user, then restart the bootstrap installation.

Maybe the systems' version of Perl installation tools is too old.

> postgreSQL database.
> I had this error
> > DBD::Pg::st execute failed: ERROR:  relation "pg_extension" does not exist
> > LINE 1: SELECT extname FROM pg_extension;
> > ^ at /home/taranis/sources/taranis-3.4.4/install/422.postgres-startup line
> so I had to install manually postgresql 9

This is one of the differences between distribution releases: there are libraries with newer versions of postgresql, but how to connect to them differs per major release.  When not connected correctly, you get the default postgresql which is too old.

> xml configuration
> it seems that some xml file has to be recoverd from /opt/taranis/conf ... and my installation was a new one ... (finally I just copy all sources/taranis*/conf files to /opt/taranis/conf and it ran)

I am interested in the message you got there.  Where has been a minor change with this in 3.4.4, which should have been an improvement... not break things.

> Startfile and conf files
> Some file require to start processes with systemctl .. but on Centos 6  I didn't have.
> so I change these lines

I have circumventions for this in the RedHat6 support scripts, which could get enabled for CentOS 6 as well.  However, as said... no support for CentOS 6 (yet)

Look for differences between 'install/*-redhat' and 'install/*-centos'.
 
> So this issue is more regarding github :) . How can I help and commit these information, will I be able to do this on my own or not?

Of course you can always create a fork.  When your patch is in the lines as our RedHat 6 configuration works, I may even merge it ;-)

> Another issue is regarding a basic "how to", you had pdf file on taranis.ncsc websit, I had delete everything. I don't understand yet how to use some tools you provide, and some on taranis4u .will it be available somewhere?

The information of taranis.ncsc.nl was stalled... got removed too late.  All documentation about installing (and working with) Taranis 3.4 has moved to the wiki of this github repo (see the top bars of this page)

 > feel free to contact me about this.

No idea who 'me' is.

**Comment by ivmp-ewl** [comment]
Hello, 

You are right, this is not really issue ... but my experience on my installation. I wanted to share what I met (and now it's running on my Centos6). I will look to perform a fork and then ask you for a merge ... but will see later.
Anyway thanks for your answer, I'll ask more questions to taranis@ncsc.nl regarding "how to". 

Regards
