### ISSUE TITLE
Meta-Search Rewrite: _wordFilterFind with multiple id_fields

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#15]
We need multiple fields for distinct identification of a single record of our module. Will you implement a solution to enable passing multiple id_fields to search-funtions? F.e. we need to pass the fields "id" and "version".

**Comment by markov2** [comment]
* bsi-lz (notifications@github.com) [190204 16:48]:
> We need multiple fields for distinct identification of a single record
> of our module. Will you implement a solution to enable passing multiple
> id_fields to search-funtions? F.e. we need to pass the fields "id" and
> "version".

Sorry, this request is too abstract for me to understand.  Can you
include an example usage?

Adding search fields and tables is actually quite difficult: it's simple
to kill all performance :-(   Therefore, the request for extension must
be very explicit.

(Be warned: search in 3.5.0 is broken)
-- 
               MarkOv

**Comment by bsi-lz** [comment]
No worries. Here is a working SQL-Statement created with your code and my (ugly) changes:  

`SELECT se.id, se.title, se.comments AS description, se.idstring, se.version, se.max_version, se.rev, se.max_rev, TO_CHAR(se.creation_datetime, 'DD-MM-YYYY HH24:MI:SS:MS') AS date
FROM sitentry AS se
   WHERE (se.id, se.version) IN (
      SELECT id ,version  
         FROM sitentry
            WHERE title ILIKE '%test%' OR comments ILIKE '%test%' OR id ILIKE '%test%' OR idstring ILIKE '%test%'   )`  

> (Be warned: search in 3.5.0 is broken)

i cannot say that - its working for us - at least for items and our module "sitentry"

**Comment by markov2** [comment]
No plans to make the meta-search interface pluggable.  Constructing search queries is fragile: small changes may have big impact on the performance.  With such complex changes, you should create your own branch on git maintaining them.
