### ISSUE TITLE
warning: the following paths have collided

### ISSUE THREAD

**Issue by edwinschaap** [NCSC-NL/taranis3#18]
A git clone leaves me with the following error:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'taranis4u/assets/img/source_icons/CNET.gif'
  'taranis4u/assets/img/source_icons/cnet.gif'
```

**Comment by markov2** [comment]
Gladly this is only a warning: Taranis use is restricted to some Linux distributions where case-insensitive file-systems are rare.  On the other hand, the distributed example sources only contain the lower-cased version.  The capitalized gif will be removed.

**Comment by markov2** [comment]
3.6.1 has been released, which fixes this
