### ISSUE TITLE
error when trying to use taranis bash commands

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#19]
After merging your 3.5 changes into our codebase i get following error when trying to execute the taranis bash commands:

ERROR: failed to load plugin Taranis::Command::Install from /home/taranis/taranis-3.4.0/perl5/Taranis/Command/Install.pm:
Can't locate File/Remove.pm in @INC (@INC contains: /home/taranis/taranis-3.4.0/perl5 /home/taranis/ChartDirector/lib /home/taranis/lib/perl5/x86_64-linux-thread-multi /home/taranis/lib/perl5 /home/taranis/sources/taranis-3.4.0/pm /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/taranis/taranis-3.4.0/perl5/Taranis/Command/Install.pm line 12, <DATA> line 1003.
BEGIN failed--compilation aborted at /home/taranis/taranis-3.4.0/perl5/Taranis/Command/Install.pm line 12, <DATA> line 1003.
Compilation failed in require at (eval 425) line 1, <DATA> line 1003.
BEGIN failed--compilation aborted at (eval 425) line 1, <DATA> line 1003.

I can not find the File::Remove.pm anywhere in your 3.5 package...

**Comment by bsi-lz** [comment]
i guess its installed vie CPAN during installation?

**Comment by markov2** [comment]
* bsi-lz (notifications@github.com) [190211 16:05]:
> i guess its installed vie CPAN during installation?

Good guess.

Oy, I introduced a new chick-n-egg problem.
As user taranis, try "cpan -i File::Remove"
Needs to get fixed in 3.5.1
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by bsi-lz** [comment]
That helped. Thanks alot

**Comment by markov2** [comment]
This should have been fixed in 3.6.0, but probably wasn't.  Extended fix in 3.6.2
