### ISSUE TITLE
Post-install error

### ISSUE THREAD

**Issue by dmoore44** [NCSC-NL/taranis3#26]
Hello,

I just completed the bootstrap install and upon navigating to `serveraddress.com:83/taranis/`, I was greeted with an Internal Server error. I checked `/var/log/taranis/taranis-3.6.2/apache/error_log` and saw the following:

`[Tue Dec 17 18:10:00.600947 2019] [:error] [pid 54737:tid 140031751816960] Can't locate Devel/GlobalDestruction.pm in @INC (you may need to install the Devel::GlobalDestruction module) (@INC contains: /home/taranis/taranis-3.6.2/perl5 /home/taranis/lib/perl5/x86_64-linux-gnu-thread-multi /home/taranis/lib/perl5 /home/taranis/lib/perl5/x86_64-linux-gnu-thread-multi /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /etc/apache2) at /home/taranis/taranis-3.6.2/perl5/Taranis/DB.pm line 413.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/perl5/Taranis/DB.pm line 413.\nCompilation failed in require at /home/taranis/taranis-3.6.2/perl5/Taranis/Database.pm line 24.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/perl5/Taranis/Database.pm line 24.\nCompilation failed in require at /home/taranis/taranis-3.6.2/perl5/Taranis/SessionUtil.pm line 19.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/perl5/Taranis/SessionUtil.pm line 19.\nCompilation failed in require at /home/taranis/taranis-3.6.2/modperl/index.pl line 16.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/modperl/index.pl line 16.\n`

Where would I go from here?

**Comment by dmoore44** [comment]
Nevermind - `cpan -i Devel::GlobalDestruction` and then restarting apache seems to have done the trick.

**Comment by markov2** [comment]
* Dallas Moore (notifications@github.com) [191217 18:16]:
> Hello,
> 
> I just completed the bootstrap install and upon navigating to `serveraddress.com:83/taranis/`, I was greeted with an Internal Server error. I checked `/var/log/taranis/taranis-3.6.2/apache/error_log` and saw the following:
> 
> `[Tue Dec 17 18:10:00.600947 2019] [:error] [pid 54737:tid 140031751816960] Can't locate Devel/GlobalDestruction.pm in @INC (you may need to install the Devel::GlobalDestruction module) (@INC contains: /home/taranis/taranis-3.6.2/perl5 /home/taranis/lib/perl5/x86_64-linux-gnu-thread-multi /home/taranis/lib/perl5 /home/taranis/lib/perl5/x86_64-linux-gnu-thread-multi /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /etc/apache2) at /home/taranis/taranis-3.6.2/perl5/Taranis/DB.pm line 413.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/perl5/Taranis/DB.pm line 413.\nCompilation failed in require at /home/taranis/taranis-3.6.2/perl5/Taranis/Database.pm line 24.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/perl5/Taranis/Database.pm line 24.\nCompilation failed in require at /home/taranis/taranis-3.6.2/perl5/Taranis/SessionUtil.pm line 19.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/perl5/Taranis/SessionUtil.pm line 19.\nCompilation failed in require at /home/taranis/taranis-3.6.2/modperl/index.pl line 16.\nBEGIN failed--compilation aborted at /home/taranis/taranis-3.6.2/modperl/index.pl line 16.\n`
> 
> Where would I go from here?


   su - taranis
   cpan -i Devel::GlobalDestruction
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net
