### ISSUE TITLE
Creating sources

### ISSUE THREAD

**Issue by dmoore44** [NCSC-NL/taranis3#27]
Having an odd issue... Whenever I try to create a source, Taranis just kind of hangs after I click save. I think it might have something to do with the image file I'm attempting to upload... but the image complies with the requirements (72x30, gif).  Anything I could be doing incorrectly?

**Comment by dmoore44** [comment]
I can create a source if I use a jpeg or some other image format. But if I do, when I try to edit the source, the source name and image information have disappeared and there's no entries in the saved sources list.

**Comment by markov2** [comment]
I expect it is another module (version) issue.  Did not hear about this before.  Maybe some database error message.

Please send me some system details to me (mark@overmeer.net)  OS versions, Taranis version, ...

**Comment by still42** [comment]
I had a similar error, but only had problems when Taranis could not access the folder where the images are located. After fixing the access rights taranis works as expected.
