### ISSUE TITLE
Will 3.5.0 also be released on Github?

### ISSUE THREAD

**Issue by cudeso** [NCSC-NL/taranis3#3]
Hello,

Will v3.5.0 also be released on Github? Couldn't find any branch referencing v3.5.0
Was espc. interested in the "taranis db remove-items" option.

thanks!

koen

**Comment by rkokkelk** [comment]
Hi Koen,

Yes Taranis version 3.5.0 will be released on this Github repo. Currently we are developing primarily in another private repository. But once a new version is ready for release we will update this repo accordingly. 

So although you don't see any branches, etc, relevant to the new version, we are currently working very hard to release it as soon as possible.
