### ISSUE TITLE
/taranis/var/cron.often ad /taranis/var/cron.cycle generates error

### ISSUE THREAD

**Issue by ScorpionKing34** [NCSC-NL/taranis3#30]
/taranis/var/cron.often:
argument "" isn't numeric in numeric gt (>) at /taranis/taranis-3.6.2-templates/dashboard_write.tt line 59
On this line = [% END %]

/taranis/var/cron.cycle:
ERROR: no cluster configured
We don't uses clusters.

How can I resolve this issue?

**Comment by markov2** [comment]
To separate issues.  AFAIK, the 'dashboard_write.tt' one is just a warning, which disappears when the cron.cycle and cron.daily have run at least once.  The "dashboard" page (front page) generation lacks some details at start.

The second error is probably correct.  ~taranis/var/cron.cycle starts various cycle activities, one after the other.  You can simply edit that script to disable "$TARANIS cluster news-items" on line 38  (Do not forget to document that in your own installation notes)

Neither issue should block your service

**Comment by ScorpionKing34** [comment]
reply to 'To separate issues. AFAIK, the 'dashboard_write.tt' one is just a warning, which disappears when the cron.cycle and cron.daily have run at least once. The "dashboard" page (front page) generation lacks some details at start.':  cron.cycle and cron.daily was running but still we get this error.

**Comment by markov2** [comment]
I think it is only a warning, so shouldn't harm you.  But we may (finally) be able the fix it.

The line number is the end-of-file, because the whole template get compiled into one Perl function call... the problem can be anywhere.  Can you try this fix:
```diff
*** templates/dashboard_write.tt	2019-11-27 10:38:44.422281196 +0100
--- templates/dashboard_write.tt.new	2020-02-17 09:25:13.066009300 +0100
***************
*** 28,34 ****
  				[% END %]
  				</div>
  			</div>
! 			[% IF endOfDayStatus || ( collectorNotifications && collectorNotifications.data.size > 0 ) %]
  			<hr class="light">
  			[% END %]
  		[% END %]
--- 28,34 ----
  				[% END %]
  				</div>
  			</div>
! 			[% IF endOfDayStatus || ( collectorNotifications && collectorNotifications.data && collectorNotifications.data.size > 0 ) %]
  			<hr class="light">
  			[% END %]
  		[% END %]
```
It is the only place which I can see a 'guard' is missing on '>'.   Apply to `~taranis/taranis-3.6.2/templates/dashboard_write.tt`

**Comment by ScorpionKing34** [comment]
What do you mean 'guard' is missing on '>' ? where?

**Comment by markov2** [comment]
That line is my attempt to explain the patch.

The internals (somewhere in `script/mod_*/*.pl`) are written in such a way that `collectorNotifications.data.size` can be undef: that `data` array can be missing.  The `collectorNotifications && collectorNotifications.data` part of each `[% IF %]` avoid the size comparison with `> 0`: those parts "guard" the comparison.

On the indicated line (see patch), one guard was missing... that may cause your warning.

**Comment by ScorpionKing34** [comment]
So, the solution is to put ':' after the '0'?

**Comment by ScorpionKing34** [comment]
I am trying to understand your finding, but I don't see the solution.  which patch?

**Comment by markov2** [comment]
My comment, which you quoted before contains a patch (a diff).  Can't you see it on GitHub?  I'll send you a screen dump of what i see by mail.

**Comment by ScorpionKing34** [comment]
This issue can be closed. I have two new issues.
