### ISSUE TITLE
Links in emails are dead

### ISSUE THREAD

**Issue by dnmvisser** [NCSC-NL/taranis3#31]
Hi

I'm subscribed to the End-of-week newsletter from NCSC. This newsletter contains useful information, including a number of referenced URLs at the bottom of the message.
However, most of those URLs are truncated, rendering them useless.
I've reported this to NCSC in July 2018 (more than 18 months ago) but the emails still contain dead links.
The problem appears to originate from the fact that the the body is hard truncated to 71 characters (for example at https://github.com/NCSC-NL/taranis3/blob/release-3.6/scripts/mod_write/eow.pl#L229).

This shouldn't be too difficult to fix, but there are several places where this truncation happens, and I'm not sure which affect email formatting.

**Comment by markov2** [comment]
Official answers when you submit your questions to taranis@ncsc.nl  However, I can give you an unofficial answer.

The messages get PGP-signed.  The signer will chop lines somewhere at 72 chars... cannot be circumvented.  To avoid uncontrolled chopping, we fold the lines ourselves.  Many links are longer than 60-something characters so always get corrupted.

The same happens in advisories.  I need all kinds of magic to restore the links when I convert the plain text messages into html for https://advisories.ncsc.nl

If we would have used PGP-encrypted, not -signed, than this problem would not exist.

**Comment by thijskh** [comment]
There should be no problem with line folding when using PGP/mime attached signatures instead of inline signing of the messages?

**Comment by markov2** [comment]
> There should be no problem with line folding when using PGP/mime attached signatures instead of inline signing of the messages?

Agree
