### ISSUE TITLE
Advisory has not been sent from taranis

### ISSUE THREAD

**Issue by chandog** [NCSC-NL/taranis3#32]
I cant send published advisories from taranis instead we get below emails from our mail boxes

Argument "" isn't numeric in numeric gt (>) at /home/taranis/taranis-3.6.2/templates/dashboard_write.tt line 59.

**Comment by markov2** [comment]
"I cant send" is far too generic for me to respond to.

The message is an unrelated warning.  It happens with all versions < 3.7 (3.7 not yet released: in the testing phase)

**Comment by chandog** [comment]
This is just a warning

**Comment by chandog** [comment]
Hello Mark
We have configured taranis to send emails to a specific email address we are getting response "Advisory has not been sent." Please note postfix has been properly configured

**Comment by markov2** [comment]
It is easier (and more private) to use email to debug your problem.  Please contact me at mark@overmeer.net

**Comment by chandog** [comment]
Hello Mark. This is noted. I have checked you through email
