### ISSUE TITLE
Errormessages from cron job

### ISSUE THREAD

**Issue by SigurddeJongNcsc** [NCSC-NL/taranis3#37]
We get a lot of emails from cron with message:
Use of uninitialized value in subroutine entry at /opt/taranis/taranis-3.6.2/perl5/Taranis/DB.pm line 207
my $size = $dbh->func($lobj_fd, $[1], length $[1], 'lo_write');

Can you help us find out what they mean and how to solve them?

**Comment by markov2** [comment]
Did not get more info
