### ISSUE TITLE
How to write new Publications in taranis

### ISSUE THREAD

**Issue by chandog** [NCSC-NL/taranis3#38]
We want Taranis to send  other publications in addition to the existing ones.
Is it possible to add publications in Taranis since below are the only options that we have now

•	Taranis Advisory
•	Taranis Advisory Forward
•	End-of-Day
•	End-of-Shift
•	End-of-Week

**Comment by markov2** [comment]
Writing publications does not provide a pluggable infrastructure, so: only with quite a lot of effort.  You may fork our public branch to add it: it needs modification on quite a number of places.

**Comment by chandog** [comment]
Ooh ok that is noted.
In existing publication templates.
Is there a possibility of adding new features e.g. logo?

**Comment by markov2** [comment]
Taranis started a long time ago... my guess is at least 15 years ago.  Back in the time everyone (sensibly) mailed plain text around.  So: all components are plain text and the constructed advisory is in plain text as well.  Plain text does not support logo's.

You can easily add (plain text) components to your message templates.

Also, I wrote a "plain text to html" converter to be able to nicely display advisories on [our website ](https://advisories.ncsc.nl/advisories)  You could use that in a milter.

**Comment by markov2** [comment]
Discussion discontinued so closed
