### ISSUE TITLE
unexpected behavior under Assess by using BulkAnalysis with an itemcluster and a single item

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#4]
Using the BulkAnalysis function by selecting an itemcluster and a single item should create an analysis which is linked to all items of the cluster and the single item.
Actually only the top item of the cluster and the single item will be linked to the analysis. The BulkAnalysis radiobutton "Link all clustered items to analysis." was selected.

BulkAnalysis with one cluster, or with many single items behaves like expected (linking all items to the analysis)

**Comment by markov2** [comment]
After a painful investigation, it turned out to simply be a mis-naming of a flag, which was not discovered for five years.  (Internal issue number 213)

**Comment by rkokkelk** [comment]
Difficult to test locally due to the limit sources used, which does not result in clusters. Therefore test in Acceptance with more sources and thus a higher chance for the generation of clusters.

**Comment by markov2** [comment]
Fix released in 3.6.1
