### ISSUE TITLE
Unread / Read / Important / Waitingroom use cases

### ISSUE THREAD

**Issue by kmizeta** [NCSC-NL/taranis3#42]
Hello,

can you please explain the use case in the assess section, for the following specific classifications?
- Unread / Read: understood
- Important
- Waitingroom

Thanks!

**Comment by markov2** [comment]
* kmizeta (notifications@github.com) [201102 15:31]:
> can you please explain the use case in the assess section, for the
> following specific classifications?
> - Unread / Read: understood

> - Important

You can mark items to be important via the 'mark as important', so
your colleagues are informed.  The item list is refreshed regularly,
so they will see it eventually. I do not think it's more than that.

> - Waitingroom

One or more items are used to start an analysis.  Those are marked
"waitingroom".  I have no idea why it has that name: it's more like
"selected to be useful".

Does this explanation suffice?
-- 
Regards,
               MarkOv

**Comment by kmizeta** [comment]
Thanks MarkOv, the answer may seem obvious but i needed to understand how you are using it.

Regards
Kmizeta
