### ISSUE TITLE
#Taranis customization to gatherening vulnerabilities by ours products (in my IT assets).

### ISSUE THREAD

**Issue by hsninbil** [NCSC-NL/taranis3#43]
Hello everyone, I want to customize the taranis to collect the vulnerabilities aligned (/or only dedicated) to my assets (my Information system scope).
Thank you

**Comment by markov2** [comment]
As answered before: this is a very generic question.  Please be more specific.  Can you describe your needs in a few more sentences and/or a functional design drawing?

**Comment by markov2** [comment]
No details received, so cannot answer the question.
