### ISSUE TITLE
Running taranis3 project in docker

### ISSUE THREAD

**Issue by ihebski** [NCSC-NL/taranis3#49]
I have created a **docker image** to run the taranis project on containers, the currently used version is a standalone image hosting the latest version 3.7.5, I am looking forward to separate the database from the web application.

Please check the image under the following link and if you agree you can update the wiki page to add this part.

https://hub.docker.com/r/ihebski/taranis3.7.5

Thank you,
Best Regards.

**Comment by donserdal** [comment]
@ihebski Do you have a dockerfile for me?

**Comment by donserdal** [comment]
Got it running, I just wanted to check the file and if possible convert it to alpine not ubuntu 18
