### ISSUE TITLE
Configuration of ID Patterns: Patterns cannot be deleted

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#5]
Deleting an ID Pattern under "Taranis Configuration -> Collector configuration -> ID Patterns" is not working. 
For example trying to delete "AusCERT advisory AA" creates a popup "Are you sure you want to delete this pattern?". After accepting this, the entry it is apparently gone. But by reloading it appears again.

**Comment by markov2** [comment]
Released 3.4.2
