### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by Chaima12-3** [NCSC-NL/taranis3#56]
Bonjour
j'ai faire la connexion de twitter source dans taranis mais j'ai un problème elle ne s'ajout pas aux access.
Quelle est la solutions s'il vous plait??

**Comment by markov2** [comment]
Hi.  Only conversations in English please, so other people can benefit from the responses as well.

You need to apply this patch by hand: pull request https://github.com/NCSC-NL/taranis3/pull/44
I am waiting for the final tests of Taranis release 3.8 which includes these changes.

Without any details, it is hard to debug your problem.  And even with that information, when I have no access to your keyboard.  To configure twitter, you need to fill in 4 fields in `~/etc/taranis.conf.xml`, named `twitter_*`.

**Comment by Chaima12-3** [comment]
what are the 4 fields that will be add to ~/etc/taranis.conf.xml???

**Comment by markov2** [comment]
Sorry: as issue #44 describes: replace 4 old configuration lines by 1 new.  When you have more questions about that patch, then please reply to that issue.
