### ISSUE TITLE
Create parser for JSON payloads

### ISSUE THREAD

**Issue by ihebski** [NCSC-NL/taranis3#59]
Some feeds are in JSON format.

**Comment by ihebski** [comment]
Hello @markov2  this is an exemple of the feeds that i would like to integrate [https://cvetrends.com/api/cves/24hrs](https://cvetrends.com/api/cves/24hrs)

**Comment by markov2** [comment]
Any idea where I can find a description of the content of the JSON?  I cannot find any docs with the interface (nor a reference to the interface on the normal pages of that website).

I can forward your request to the product owner.
