### ISSUE TITLE
Asses2Analyse: Analysis (search) is not working

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#6]
In the Asses2Analyse dialogue (where items can be pushed to the analysis) the search function under " Analysis (search)" is not working. 

assess2analyze.js throws an error (Line 251) in the method searchAssessAnalysisCallback( params ).
a.id.substr() is not a method!

Fix: Cast to String -> String(a.id).substr()

**Comment by markov2** [comment]
Once upon a time, JSON modules in perl became kind-of typed :-(

**Comment by markov2** [comment]
Released 3.4.2
