### ISSUE TITLE
Inusfficient implemented User Rights under Analysis when set to read-only

### ISSUE THREAD

**Issue by bsi-lz** [NCSC-NL/taranis3#7]
Creating a user with a new User Role which has only the following rights:
- generic: read
- analysis: read

This user can still edit all analysis (add comments, set status, set rating) by clicking on the title of the analysis. Further the user can use the tagging function to add tags and can set himself as the owner of the analysis. 
I would expect, that the user can only read the analysis without making changes.
Maybe this is also a problem under Assess.

**Comment by markov2** [comment]
A typo in a variable name.  Internal issue number 214.

**Comment by markov2** [comment]
This is probably fixed: there are different opinions on what the various entitlements really mean.  IMHO, this issue is handled sufficiently.
