### ISSUE TITLE
Perl ChartDirector not installed automatically

### ISSUE THREAD

**Issue by mr-torgue** [NCSC-NL/taranis3#8]
The download url in 'install/500.chartdirector' is outdated, it has an untrusted certificate, so it will not be downloaded and installed. I changed the url from 'http://download2.advsofteng.com/chartdir_perl_linux_64.tar.gz' to 'http://www.advsofteng.net/chartdir_perl_linux_64.tar.gz' and after restarting httpd and taranis it worked again. Without ChartDirector the statistics menu is not available.

Why is this package manually downloaded and not using cpan?

**Comment by markov2** [comment]
That link issue is new to me, probably a recent change.  Just in time for release 3.4.2, due today.  (Internal issue number 224)

As far as I can see, Chartdir is not on CPAN so cannot be installed using CPAN.

**Comment by mr-torgue** [comment]
I thought I saw ChartDirector on cpan but it turns out it isn't. 
Great that it will be added to 3.4.2.

**Comment by markov2** [comment]
Released 3.4.2
