### ISSUE TITLE
Illegal Version Number

### ISSUE THREAD

**Issue by akok-svb** [NCSC-NL/taranis3#9]
Wanneer ik probeer te installeren, geeft hij een ERROR. Hieronder staat mijn commando en de output.

`[root@taranis ~]# ./taranis-bootstrap taranis-3.4.2\ \(1\).tar.gz
*** bootstrap installation of taranis-3.4.2 (1).tar.gz
group taranis already exists (gid=1000)
user taranis already exists (uid=1000)
*   unpacking sources into /home/taranis/sources
*** running /home/taranis/sources/taranis-3.4.2/install/010.distributions
*   running on CentOS Linux 7 (Core)
*   distribution CentOS Linux 7 (Core) is supported.
*** running /home/taranis/sources/taranis-3.4.2/install/011.distribution-opensuse
*   skipped: not running on openSUSE.
*** running /home/taranis/sources/taranis-3.4.2/install/012.distribution-centos
*   install CentOS packages:
    epel-release wget sudo lbzip2 rsync expat-devel make gcc gcc-c++
    perl-JSON perl-YAML perl-version perl-CPAN perl-Data-Dumper
    policycoreutils-python
Package epel-release-7-11.noarch already installed and latest version
Package wget-1.14-15.el7_4.1.x86_64 already installed and latest version
Package sudo-1.8.19p2-14.el7_5.x86_64 already installed and latest version
Package lbzip2-2.5-1.el7.x86_64 already installed and latest version
Package rsync-3.1.2-4.el7.x86_64 already installed and latest version
Package expat-devel-2.1.0-10.el7_3.x86_64 already installed and latest version
Package 1:make-3.82-23.el7.x86_64 already installed and latest version
Package gcc-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Package gcc-c++-4.8.5-28.el7_5.1.x86_64 already installed and latest version
Package perl-JSON-2.59-2.el7.noarch already installed and latest version
Package perl-YAML-0.84-5.el7.noarch already installed and latest version
Package 3:perl-version-0.99.07-3.el7.x86_64 already installed and latest version
Package perl-CPAN-1.9800-292.el7.noarch already installed and latest version
Package perl-Data-Dumper-2.145-3.el7.x86_64 already installed and latest version
Package policycoreutils-python-2.5-22.el7.x86_64 already installed and latest version
*** running /home/taranis/sources/taranis-3.4.2/install/013.distribution-redhat
*   skipped: not running on RedHat.
*** running /home/taranis/sources/taranis-3.4.2/install/014.distribution-ubuntu
*   skipped: not running on Ubuntu.
*** running /home/taranis/sources/taranis-3.4.2/install/1.upgrade-adv-templs
*** running /home/taranis/sources/taranis-3.4.2/install/100.release-setup
Change default version to 3.4.2.
*   creating initial release configuration for '3.4.2'
*   website will be available on port 86 (and maybe the default port)
*** running /home/taranis/sources/taranis-3.4.2/install/110.directories
*   create generic directories
Change owner to 1000/100 on /home/taranis/sources
Change mode to 0770 on /home/taranis/run
*   create directories for release 3.4.2
Create directory /tmp/taranis/taranis-3.4.2
Change mode to 0775 on /home/taranis/run
Create directory /var/log/taranis/taranis-3.4.2
Create directory /var/log/taranis/taranis-3.4.2/apache
Create directory /var/log/taranis/taranis-3.4.2/collector-errors
Create directory /home/taranis/taranis4u-3.4.2
Create directory /home/taranis/taranis-3.4.2
Create directory /home/taranis/taranis-3.4.2/perl5
Create directory /home/taranis/taranis-3.4.2/modperl
Create directory /home/taranis/taranis-3.4.2/bin
Create directory /home/taranis/taranis-3.4.2/man
Create directory /home/taranis/taranis-3.4.2/man/man1
Create directory /home/taranis/taranis-3.4.2/man/man3
Create directory /home/taranis/taranis-3.4.2/clustering
Create directory /home/taranis/taranis-3.4.2/conf
*** running /home/taranis/sources/taranis-3.4.2/install/120.profile
*   creating login version switch in /home/taranis/lib/bash_profile
ERROR: illegal version number '3.4.3.tar.gz'
Installation stopped
`

Dit gebeurd ook wanneer ik de versie 3.4.3 probeer te installeren. Op het moment is versie 3.4.1 geïnstalleerd.

**Comment by markov2** [comment]
I suspect you have tarans-3.4.3.tar.gz in the /home/taranis/ ?  Move it to /tmp and the problem will disappear.

Before this complaint, I was not aware of this but will fix it (probably 3.6.0)

**Comment by akok-svb** [comment]
> I suspect you have tarans-3.4.3.tar.gz in the /home/taranis/ ? Move it to /tmp and the problem will disappear.
> 
> Before this complaint, I was not aware of this but will fix it (probably 3.6.0)

Thank you, this was the problem indeed, it now installs perfectly fine!

**Comment by akok-svb** [comment]
It does seem to give the following error now, when installing 3.4.3, is this something related or a quick fix? 

`File does not exist: /root/etc/taranis.conf.xml at /home/taranis/sources/taranis-3.4.3/pm/Taranis/Config.pm line 21.
`

**Comment by markov2** [comment]
* akok-svb (notifications@github.com) [181001 07:45]:
> It does seem to give the following error now, when installing 3.4.3,
> is this something related or a quick fix?
> 
> `File does not exist: /root/etc/taranis.conf.xml at
> /home/taranis/sources/taranis-3.4.3/pm/Taranis/Config.pm line 21.

See https://github.com/NCSC-NL/taranis3/wiki/Release-3.4.3
under "Known issues"
-- 
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by markov2** [comment]
The initial reported issue has internal tracking number 241, and now has a patch to be included in 3.6
